#!/bin/bash
#
# Alex Vesev @ ALT Linux, 2012-10-05
#
##
 
declare -r maintainerName="builder"
declare -r maintainerMail="builder@altlinux.org"
 
declare -r dirSandBoxTopOrig="${HOME}/hsh-sandbox/sisyphus-x86_64"
declare -r dirSandBoxTop="/tmp/.private/builder/hsh-sandbox/sisyphus-x86_64"
declare -r dirSandBoxHasher="${dirSandBoxTop}/hasher"
declare -r optDirRepoHasher="--repo=\"${dirSandBoxTop}/repo/...\"" # XXX - применение не реализовано.
 
declare -r archTarget="x86_64"
 
#declare -r argNoCheck="--no-sisyphus-check"
declare -r argNoCheck="--no-sisyphus-check=packager,gpg"
 
function showDoc {
    cat "${0}"
}
 
[ "${#}" == 0 ] \
    && showDoc \
    && exit 1
 
cliArgument="${1}"
cliOptionName="${cliArgument%%=*}"
cliOptionName="${cliOptionName#--}"
cliOptionValue="${cliArgument#*=}"
 
mkdir -p "${dirSandBoxHasher}"
cp "${dirSandBoxTopOrig}/"* "${dirSandBoxTop}/"

case "${cliOptionName}" in
shell|sh)
    hsh-shell --mountpoints="/proc" "${dirSandBoxHasher}"
;;
build|bu)
    gear \
	--verbose \
	--commit \
	--hasher \
	-- ${archTarget} \
	hsh \
	    --verbose \
	    --nprocs=16 \
	    --packager="${maintainerName} <${maintainerMail}>" \
	    ${argNoCheck} \
	    --target=${archTarget} \
	    --lazy-cleanup \
            --mountpoints="/proc,/dev/pts,/sys" \
	    --apt-config="${dirSandBoxTop}/apt.conf" \
	    "${dirSandBoxHasher}"
# --mountpoints="/proc,/dev/pts,/sys" \
;;
rebuild|reb|rebu)
    gear \
	--verbose \
	--commit \
	--hasher \
	-- ${archTarget} \
	hsh-rebuild \
	    --verbose \
	    ${argNoCheck} \
	    --target=${archTarget} \
	    --mountpoints="/proc,/dev/pts,/sys" \
	    "${dirSandBoxHasher}"
;;
install|ins)
    shift 1
    hsh-install "${dirSandBoxHasher}" "${@}"
;;
clean-all)
    hsh --cleanup-only "${dirSandBoxHasher}"
;;
esac
